version: '3.8'

services:
  log-parser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: log-parser-local
    volumes:
      - ./server.log:/app/server.log:rw

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: log-frontend
    ports:
      - "8080:80"

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: log-backend
    ports:
      - "4001:4000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: database_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./apps/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@db:5432/appdb?sslmode=disable"
    ports:
      - "9187:9187"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend
      - postgres-exporter

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

volumes:
  pgdata: